### ISSUE TITLE
Incoming mail error

### ISSUE THREAD

**Issue by arh-space** [JReverse/TMail-Nulled#1]
thank you for sharing the script, I installed it without a problem, but there was no incoming email i have checked imap and database, when the email is opened an error occurs like ops something went wrong, what's wrong with that?

![1](https://user-images.githubusercontent.com/65483182/93734575-07412500-fc04-11ea-9a97-28d9b15787a2.JPG)

**Comment by JReverse** [comment]
Only works on cpanel only host i tried https://hostkoala.com/

**Comment by Cody005** [comment]
I got same error, i created a DB and everything went smooth but when i open the page i got this error

**Comment by Cody005** [comment]
> Only works on cpanel only host i tried https://hostkoala.com/

but all cpanel its the same? right
