### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by noxplayer2021** [JReverse/TMail-Nulled#7]
Hello JReverse,
Currently, TMail v6.3 has been released. So could you please update it to the new version? Thanks! Wish you good health, great job !!!

**Comment by JReverse** [comment]
soon don't expect updates the day of release.

**Comment by noxplayer2021** [comment]
Hello! I have a little question I want to ask you:
Did you buy TMail or where did you get the TMail source code?

**Comment by noxplayer2021** [comment]
Hello! Are you still active on Github? Please update TMail to the latest version. Version 6.4 is out now, but you're still at version 6.2. So can you update it to the new version? Thanks!!

**Comment by JReverse** [comment]
@noxplayer2021 Done.
